/*
  HTML_Slide_Editor Engine v1.0
  TEMPLATE_LOCKED_AREA: JAVASCRIPT / EDITOR ENGINE
  Do not edit this file from a deck-specific HTML request unless the user explicitly asks to change editor behavior.
  Deck-specific content belongs in the deck-data JSON script block inside each HTML file.
*/
(() => {
      const imageInput = document.createElement("input");
      imageInput.type = "file";
      imageInput.accept = "image/*";
      imageInput.hidden = true;
      document.body.appendChild(imageInput);

      let activeImageBox = null;
      let activeSlide = null;

      const deck = document.querySelector(".deck");
      const dataEl = document.querySelector("#deck-data");
      const templateTypes = [
        ["cover", "표지"],
        ["toc", "목차"],
        ["message", "메시지"],
        ["two-col", "2카드"],
        ["cards", "4카드"],
        ["image", "이미지"],
        ["visual-note", "비주얼노트"]
      ];
      const themeTypes = [
        ["gray", "Gray", "기본 흑백/그레이 톤"],
        ["blue", "Blue", "차분한 블루 톤"],
        ["purple", "Purple", "부드러운 퍼플 톤"]
      ];
      const selector = [
        "h1", "h2", "h3", "p", "li",
        ".toc-item span", ".card .step", ".panel .label", ".note-panel .label",
        ".header .label", ".header .num", ".footer .author", ".footer .date",
        ".visual-label", ".visual-note"
      ].join(",");

      const currentHtmlName = decodeURIComponent(location.pathname.split("/").pop() || "")
        .replace(/\.html?$/i, "") || "HTML_Slide_Editor";
      document.title = currentHtmlName;
      document.querySelector(".brand-mark .name").textContent = currentHtmlName;

      const escapeHtml = (value = "") => String(value)
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;");
      const multiline = (value = "") => escapeHtml(value).replaceAll("\n", "<br>");
      const uid = () => `slide-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

      const readDeckData = () => {
        try {
          return JSON.parse(dataEl.textContent.trim());
        } catch (error) {
          alert("deck-data JSON을 읽을 수 없습니다. JSON 문법을 확인하세요.");
          throw error;
        }
      };
      let deckData = readDeckData();
      deckData.slides = Array.isArray(deckData.slides) ? deckData.slides : [];
      deckData.theme = deckData.theme || localStorage.getItem("html-slide-editor-theme") || "gray";

      const writeDeckData = () => {
        const json = JSON.stringify(deckData, null, 2).replaceAll("</script", "<\\/script");
        dataEl.textContent = `\n${json}\n  `;
      };
      const slideIndex = (slide) => Array.from(deck.querySelectorAll(".slide")).indexOf(slide);
      const orderedSlides = () => Array.from(deck.querySelectorAll(".slide"));
      const dataForSlide = (slide) => deckData.slides.find((item) => item.id === slide.dataset.slideId);
      const typeLabel = (type) => templateTypes.find(([key]) => key === type)?.[1] || "장표";
      const themeLabel = (theme) => themeTypes.find(([key]) => key === theme)?.[1] || "Gray";
      const applyTheme = (theme = "gray", persist = false) => {
        const nextTheme = themeTypes.some(([key]) => key === theme) ? theme : "gray";
        document.body.classList.remove("theme-gray", "theme-blue", "theme-purple");
        document.body.classList.add(`theme-${nextTheme}`);
        deckData.theme = nextTheme;
        if (persist) {
          localStorage.setItem("html-slide-editor-theme", nextTheme);
          writeDeckData();
        }
        document.querySelectorAll(".theme-option").forEach((button) => {
          button.classList.toggle("active", button.dataset.themeValue === nextTheme);
        });
        const floating = document.querySelector(".theme-floating-button");
        if (floating) floating.setAttribute("aria-label", `디자인 템플릿 선택: ${themeLabel(nextTheme)}`);
      };

      const defaultSlide = (type = "message") => {
        const templates = {
          cover: { id: uid(), type, fields: { week: "주차명", title: "메인 타이틀\n서브 타이틀", subtitle: "강의 또는 문서의 핵심 목적을 한 문장으로 적습니다.", author: "작성자 또는 스터디명", date: "YYYY.MM.DD" } },
          toc: { id: uid(), type, fields: { title: "목차", items: [1, 2, 3, 4].map((n) => ({ number: String(n).padStart(2, "0"), title: "섹션 제목", description: "섹션에서 다룰 핵심 내용을 적습니다." })) } },
          message: { id: uid(), type, fields: { section: "Section Label", page: "01", title: "가장 강조하고 싶은 문장을 크게 배치합니다.", body: "보조 설명은 짧게 둡니다." } },
          "two-col": { id: uid(), type, fields: { section: "Section Label", page: "02", title: "2카드 레이아웃", subtitle: "두 개념의 차이, Before/After, 판단 기준 비교에 사용합니다.", panels: [{ label: "Concept A", title: "첫 번째 관점", body: "정의, 기준, 예시를 짧게 정리합니다." }, { label: "Concept B", title: "두 번째 관점", body: "정의, 기준, 예시를 짧게 정리합니다." }] } },
          cards: { id: uid(), type, fields: { section: "Section Label", page: "03", title: "4카드 레이아웃", subtitle: "핵심 내용, 분석 관점, 활용 자료, 산출물을 한 장에 정리합니다.", cards: [{ step: "01", title: "핵심 내용", body: "장표에서 설명할 핵심 개념을 적습니다." }, { step: "02", title: "분석 관점", body: "실제 서비스 분석에서 어떤 질문으로 바뀌는지 적습니다." }, { step: "03", title: "활용 자료", body: "표, 이미지, 로그, 리서치 등 참고 자료를 적습니다." }, { step: "04", title: "산출물", body: "최종적으로 남길 문서, 표, 템플릿명을 적습니다." }] } },
          image: { id: uid(), type, fields: { section: "Section Label", page: "04", title: "이미지 또는 자료 레이아웃", subtitle: "시각 자료가 필요한 장표에서 이미지 자리와 설명 메모를 함께 둡니다.", image: "", imageAlt: "이미지 또는 자료", visualLabel: "이미지/자료 자리", visualNote: "여기에 이미지, 표, 다이어그램, 캡처를 배치합니다." } },
          "visual-note": { id: uid(), type, fields: { section: "Visual Note", page: "05", title: "비주얼 노트 레이아웃", subtitle: "이미지와 설명을 나란히 두고, 강의자가 짚을 해석 포인트를 정리합니다.", image: "", imageAlt: "이미지 또는 자료", visualLabel: "이미지/자료 자리", visualNote: "캡처, 표, 다이어그램을 배치합니다.", noteLabel: "Explanation", noteTitle: "이 자료에서 무엇을 봐야 하는가", noteBody: "이미지의 핵심 관찰점, 판단 기준, 다음 액션으로 이어지는 해석을 적습니다." } }
        };
        return JSON.parse(JSON.stringify(templates[type] || templates.message));
      };

      const headerHtml = (fields, index) => `<div class="header"><div class="label">${escapeHtml(fields.section || "Section Label")}</div><div class="num">${escapeHtml(fields.page || String(index).padStart(2, "0"))}</div></div>`;
      const titleHtml = (fields) => `<div class="title"><h2>${multiline(fields.title || "제목")}</h2><p>${multiline(fields.subtitle || "")}</p></div>`;
      const imageBoxHtml = (fields) => {
        if (fields.image) return `<div class="image-box"><img src="${escapeHtml(fields.image)}" alt="${escapeHtml(fields.imageAlt || "Inserted image")}"></div>`;
        return `<div class="image-box"><div><div class="visual-label">${escapeHtml(fields.visualLabel || "이미지/자료 자리")}</div><div class="visual-note">${multiline(fields.visualNote || "여기에 이미지, 표, 다이어그램, 캡처를 배치합니다.")}</div></div></div>`;
      };

      const slideScaffold = (slideData, index) => {
        const fields = slideData.fields || {};
        if (slideData.type === "cover") return `
      <div class="cover-title">
        <div class="week">${escapeHtml(fields.week || "주차명")}</div>
        <h1>${multiline(fields.title || "메인 타이틀")}</h1>
        <p>${multiline(fields.subtitle || "")}</p>
      </div>
      <div class="footer">
        <div class="author">${escapeHtml(fields.author || "작성자 또는 스터디명")}</div>
        <div class="date">${escapeHtml(fields.date || "YYYY.MM.DD")}</div>
      </div>`;
        if (slideData.type === "toc") return `
      <div class="toc">
        <h2>${escapeHtml(fields.title || "목차")}</h2>
        <div class="toc-grid">
          ${(fields.items || []).map((item) => `<div class="toc-item"><span class="n">${escapeHtml(item.number || "")}</span><span class="t">${escapeHtml(item.title || "")}</span><span class="d">${escapeHtml(item.description || "")}</span></div>`).join("\n          ")}
        </div>
      </div>`;
        if (slideData.type === "message") return `
      ${headerHtml(fields, index)}
      <div class="center">
        <div class="quote">
          <h2>${multiline(fields.title || "가장 강조하고 싶은 문장을 크게 배치합니다.")}</h2>
          <div class="bar"></div>
          <p>${multiline(fields.body || "")}</p>
        </div>
      </div>`;
        if (slideData.type === "two-col") return `
      ${headerHtml(fields, index)}
      ${titleHtml(fields)}
      <div class="two-col">
        ${(fields.panels || []).slice(0, 2).map((panel) => `<div class="panel"><div class="label">${escapeHtml(panel.label || "Concept")}</div><h3>${escapeHtml(panel.title || "관점")}</h3><p>${multiline(panel.body || "")}</p></div>`).join("\n        ")}
      </div>`;
        if (slideData.type === "cards") return `
      ${headerHtml(fields, index)}
      ${titleHtml(fields)}
      <div class="cards">
        ${(fields.cards || []).slice(0, 4).map((card) => `<article class="card"><div class="step">${escapeHtml(card.step || "")}</div><h3>${escapeHtml(card.title || "")}</h3><p>${multiline(card.body || "")}</p></article>`).join("\n        ")}
      </div>`;
        if (slideData.type === "image") return `
      ${headerHtml(fields, index)}
      ${titleHtml(fields)}
      ${imageBoxHtml(fields)}`;
        if (slideData.type === "visual-note") return `
      ${headerHtml(fields, index)}
      ${titleHtml(fields)}
      <div class="visual-split">
        ${imageBoxHtml(fields)}
        <div class="note-panel">
          <div class="label">${escapeHtml(fields.noteLabel || "Explanation")}</div>
          <h3>${escapeHtml(fields.noteTitle || "이 자료에서 무엇을 봐야 하는가")}</h3>
          <p>${multiline(fields.noteBody || "")}</p>
        </div>
      </div>`;
        return slideScaffold(defaultSlide("message"), index);
      };

      const renderSlide = (slideData, index) => {
        const slide = document.createElement("section");
        slide.className = "slide";
        slide.dataset.slideId = slideData.id;
        slide.dataset.template = slideData.type;
        slide.setAttribute("aria-label", fieldsTitle(slideData));
        slide.innerHTML = slideScaffold(slideData, index);
        slide.addEventListener("click", () => setActiveSlide(slide));
        addTemplateTools(slide);
        initializeEditable(slide);
        initializeImageBoxes(slide);
        return slide;
      };

      const fieldsTitle = (slideData) => {
        const fields = slideData.fields || {};
        return fields.title || fields.week || typeLabel(slideData.type);
      };

      const renderDeck = () => {
        deck.innerHTML = "";
        deckData.slides.forEach((slideData, index) => deck.appendChild(renderSlide(slideData, index)));
        activeSlide = activeSlide ? orderedSlides().find((slide) => slide.dataset.slideId === activeSlide.dataset.slideId) || orderedSlides()[0] : orderedSlides()[0];
        renumberSlides();
        renderSidebar();
      };

      const addTemplateTools = (slide) => {
        slide.querySelector(".template-tools")?.remove();
        const tools = document.createElement("div");
        tools.className = "template-tools";
        tools.setAttribute("contenteditable", "false");
        const current = slide.dataset.template;
        templateTypes.forEach(([type, label]) => {
          const button = document.createElement("button");
          button.type = "button";
          button.dataset.templateType = type;
          button.textContent = label;
          button.title = `${label} 템플릿으로 변경`;
          if (type === current) button.classList.add("active");
          button.addEventListener("click", () => {
            if (current === type) return;
            if (!confirm(`${label} 템플릿으로 변경하면 이 슬라이드의 현재 내용이 새 구조로 바뀝니다. 변경할까요?`)) return;
            const existing = dataForSlide(slide);
            const replacement = defaultSlide(type);
            replacement.id = existing.id;
            const index = deckData.slides.findIndex((item) => item.id === existing.id);
            deckData.slides[index] = replacement;
            writeDeckData();
            renderDeck();
            setActiveSlide(orderedSlides()[index]);
          });
          tools.appendChild(button);
        });
        slide.prepend(tools);
      };

      const collectSlideData = (slide) => {
        const item = dataForSlide(slide);
        if (!item) return;
        const fields = item.fields || (item.fields = {});
        const text = (selector) => slide.querySelector(selector)?.innerText.trim() || "";
        fields.section = slide.querySelector(".header .label")?.innerText.trim() || fields.section;
        fields.page = slide.querySelector(".header .num")?.innerText.trim() || fields.page;
        if (item.type === "cover") {
          fields.week = text(".cover-title .week");
          fields.title = text(".cover-title h1");
          fields.subtitle = text(".cover-title p");
          fields.author = text(".footer .author");
          fields.date = text(".footer .date");
        } else if (item.type === "toc") {
          fields.title = text(".toc h2");
          fields.items = Array.from(slide.querySelectorAll(".toc-item")).map((row) => ({
            number: row.querySelector(".n")?.innerText.trim() || "",
            title: row.querySelector(".t")?.innerText.trim() || "",
            description: row.querySelector(".d")?.innerText.trim() || ""
          }));
        } else if (item.type === "message") {
          fields.title = text(".quote h2");
          fields.body = text(".quote p");
        } else if (item.type === "two-col") {
          fields.title = text(".title h2");
          fields.subtitle = text(".title p");
          fields.panels = Array.from(slide.querySelectorAll(".panel")).map((panel) => ({ label: panel.querySelector(".label")?.innerText.trim() || "", title: panel.querySelector("h3")?.innerText.trim() || "", body: panel.querySelector("p")?.innerText.trim() || "" }));
        } else if (item.type === "cards") {
          fields.title = text(".title h2");
          fields.subtitle = text(".title p");
          fields.cards = Array.from(slide.querySelectorAll(".card")).map((card) => ({ step: card.querySelector(".step")?.innerText.trim() || "", title: card.querySelector("h3")?.innerText.trim() || "", body: card.querySelector("p")?.innerText.trim() || "" }));
        } else if (item.type === "image" || item.type === "visual-note") {
          fields.title = text(".title h2");
          fields.subtitle = text(".title p");
          fields.visualLabel = text(".visual-label") || fields.visualLabel;
          fields.visualNote = text(".visual-note") || fields.visualNote;
          const img = slide.querySelector(".image-box img");
          fields.image = img?.getAttribute("src") || fields.image || "";
          fields.imageAlt = img?.getAttribute("alt") || fields.imageAlt || "이미지 또는 자료";
          if (item.type === "visual-note") {
            fields.noteLabel = text(".note-panel .label");
            fields.noteTitle = text(".note-panel h3");
            fields.noteBody = text(".note-panel p");
          }
        }
        writeDeckData();
      };

      const initializeEditable = (root = document) => {
        Array.from(root.querySelectorAll(selector))
          .filter((el) => !el.closest("script") && !el.closest(".template-tools"))
          .forEach((el) => {
            el.setAttribute("contenteditable", "true");
            el.setAttribute("spellcheck", "false");
            el.addEventListener("input", () => {
              collectSlideData(el.closest(".slide"));
              renderSidebar();
            });
          });
      };

      const setImage = (box, src) => {
        box.innerHTML = `<img src="${src}" alt="Inserted image">`;
        collectSlideData(box.closest(".slide"));
      };
      const readFile = (box, file) => {
        if (!file || !file.type.startsWith("image/")) return;
        const reader = new FileReader();
        reader.onload = () => setImage(box, reader.result);
        reader.readAsDataURL(file);
      };
      const initializeImageBoxes = (root = document) => {
        root.querySelectorAll(".image-box").forEach((box) => {
          box.title = "클릭해서 이미지 선택, 드래그 앤 드롭, 또는 이미지 붙여넣기";
          box.addEventListener("click", () => {
            activeImageBox = box;
            imageInput.click();
          });
          box.addEventListener("dragover", (event) => {
            event.preventDefault();
            box.classList.add("dragover");
          });
          box.addEventListener("dragleave", () => box.classList.remove("dragover"));
          box.addEventListener("drop", (event) => {
            event.preventDefault();
            box.classList.remove("dragover");
            readFile(box, event.dataTransfer.files[0]);
          });
        });
      };

      const slideTitle = (slide) => dataForSlide(slide)?.fields?.title?.replace(/\s+/g, " ").slice(0, 42) || "제목 없음";
      const setActiveSlide = (slide) => {
        activeSlide = slide;
        renderSidebar();
      };
      const syncOrderFromDom = () => {
        deckData.slides = orderedSlides().map((slide) => dataForSlide(slide)).filter(Boolean);
        writeDeckData();
      };
      const moveSlide = (slide, direction) => {
        const slides = orderedSlides();
        const index = slides.indexOf(slide);
        const targetIndex = index + direction;
        if (targetIndex < 0 || targetIndex >= slides.length) return;
        if (direction < 0) deck.insertBefore(slide, slides[targetIndex]);
        else deck.insertBefore(slides[targetIndex], slide);
        syncOrderFromDom();
        renderDeck();
        setActiveSlide(orderedSlides()[targetIndex]);
        activeSlide.scrollIntoView({ behavior: "smooth", block: "center" });
      };
      const deleteSlide = (slide) => {
        if (deckData.slides.length <= 1) {
          alert("마지막 장표는 삭제할 수 없습니다.");
          return;
        }
        if (!confirm("이 장표를 삭제할까요?")) return;
        const index = slideIndex(slide);
        deckData.slides = deckData.slides.filter((item) => item.id !== slide.dataset.slideId);
        writeDeckData();
        renderDeck();
        setActiveSlide(orderedSlides()[Math.max(0, index - 1)] || orderedSlides()[0]);
      };
      const addSlide = () => {
        const newSlide = defaultSlide("message");
        const index = activeSlide ? slideIndex(activeSlide) + 1 : deckData.slides.length;
        deckData.slides.splice(index, 0, newSlide);
        writeDeckData();
        renderDeck();
        setActiveSlide(orderedSlides()[index]);
        activeSlide.scrollIntoView({ behavior: "smooth", block: "center" });
      };

      const exportHtml = () => {
        orderedSlides().forEach(collectSlideData);
        const defaultName = deckData.slides[0]?.fields?.title?.trim().replace(/\s+/g, "_") || "HTML_Slide_Editor";
        const inputName = prompt("저장할 HTML 파일 이름을 입력하세요.", defaultName);
        if (inputName === null) return;
        const clone = document.documentElement.cloneNode(true);
        clone.querySelector(".page-sidebar")?.remove();
        clone.querySelector(".theme-floating-button")?.remove();
        clone.querySelector(".theme-modal")?.remove();
        clone.querySelector('input[type="file"][accept="image/*"]')?.remove();
        clone.querySelectorAll(".template-tools").forEach((el) => el.remove());
        clone.querySelectorAll("[contenteditable]").forEach((el) => el.removeAttribute("contenteditable"));
        clone.querySelectorAll(".dragover").forEach((el) => el.classList.remove("dragover"));
        const html = `<!doctype html>\n${clone.outerHTML}`;
        const blob = new Blob([html], { type: "text/html;charset=utf-8" });
        const link = document.createElement("a");
        const now = new Date();
        const stamp = [now.getFullYear(), String(now.getMonth() + 1).padStart(2, "0"), String(now.getDate()).padStart(2, "0"), String(now.getHours()).padStart(2, "0"), String(now.getMinutes()).padStart(2, "0")].join("");
        const safeName = inputName.trim().replace(/\.html?$/i, "").replace(/[\\/:*?"<>|]/g, "_").replace(/\s+/g, "_").slice(0, 80);
        link.href = URL.createObjectURL(blob);
        link.download = `${safeName || `HTML_Slide_Editor_${stamp}`}.html`;
        document.body.appendChild(link);
        link.click();
        link.remove();
        setTimeout(() => URL.revokeObjectURL(link.href), 1000);
      };

      const renderThemePicker = () => {
        if (document.querySelector(".theme-floating-button")) return;
        const button = document.createElement("button");
        button.type = "button";
        button.className = "theme-floating-button";
        button.textContent = "◐";
        button.title = "디자인 템플릿 선택";
        document.body.appendChild(button);

        const modal = document.createElement("div");
        modal.className = "theme-modal";
        modal.hidden = true;
        modal.innerHTML = `
          <div class="theme-dialog" role="dialog" aria-modal="true" aria-labelledby="theme-dialog-title">
            <div class="theme-dialog-header">
              <div>
                <h2 class="theme-dialog-title" id="theme-dialog-title">디자인 템플릿</h2>
                <p class="theme-dialog-subtitle">슬라이드 내용은 유지하고 색상 톤만 변경합니다.</p>
              </div>
              <button class="theme-close" type="button" aria-label="닫기">×</button>
            </div>
            <div class="theme-grid">
              ${themeTypes.map(([value, label, desc]) => `
                <button class="theme-option" type="button" data-theme-value="${value}">
                  <span class="theme-preview" aria-hidden="true">
                    <span class="theme-preview-slide">
                      <span class="theme-preview-title"></span>
                      <span class="theme-preview-line"></span>
                      <span class="theme-preview-line short"></span>
                    </span>
                  </span>
                  <span class="theme-option-name">${label}</span>
                  <span class="theme-option-desc">${desc}</span>
                </button>
              `).join("")}
            </div>
          </div>`;
        document.body.appendChild(modal);

        const closeModal = () => {
          modal.hidden = true;
          button.focus();
        };
        button.addEventListener("click", () => {
          modal.hidden = false;
          modal.querySelector(".theme-option.active")?.focus();
        });
        modal.querySelector(".theme-close").addEventListener("click", closeModal);
        modal.addEventListener("click", (event) => {
          if (event.target === modal) closeModal();
        });
        modal.querySelectorAll(".theme-option").forEach((option) => {
          option.addEventListener("click", () => {
            applyTheme(option.dataset.themeValue, true);
            closeModal();
          });
        });
        document.addEventListener("keydown", (event) => {
          if (event.key === "Escape" && !modal.hidden) closeModal();
        });
        applyTheme(deckData.theme);
      };

      const renderSidebar = () => {
        let sidebar = document.querySelector(".page-sidebar");
        if (!sidebar) {
          sidebar = document.createElement("aside");
          sidebar.className = "page-sidebar";
          sidebar.innerHTML = `<button class="sidebar-toggle" type="button" aria-label="슬라이드 인덱스 접기" title="슬라이드 인덱스 접기"><span class="icon">◀</span></button><button class="add-slide" type="button">장표 추가</button><button class="export-html" type="button">HTML 저장</button><div class="page-list"></div>`;
          document.body.prepend(sidebar);
          sidebar.querySelector(".add-slide").addEventListener("click", addSlide);
          sidebar.querySelector(".export-html").addEventListener("click", exportHtml);
          sidebar.querySelector(".sidebar-toggle").addEventListener("click", () => {
            const collapsed = document.body.classList.toggle("sidebar-collapsed");
            const toggle = sidebar.querySelector(".sidebar-toggle");
            toggle.querySelector(".icon").textContent = collapsed ? "▶" : "◀";
            toggle.setAttribute("aria-label", collapsed ? "슬라이드 인덱스 펼치기" : "슬라이드 인덱스 접기");
            toggle.title = collapsed ? "슬라이드 인덱스 펼치기" : "슬라이드 인덱스 접기";
          });
        }
        const slides = orderedSlides();
        const list = sidebar.querySelector(".page-list");
        list.innerHTML = "";
        slides.forEach((slide, index) => {
          const item = document.createElement("div");
          item.className = `page-item${slide === activeSlide ? " active" : ""}`;
          item.innerHTML = `
            <button class="page-jump" type="button">
              <span class="page-index">${String(index + 1).padStart(2, "0")} · ${typeLabel(slide.dataset.template)}</span>
              <span class="page-title"></span>
            </button>
            <div class="page-actions">
              <button class="delete-slide" type="button" title="장표 삭제" aria-label="장표 삭제"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"></path><path d="M8 6V4h8v2"></path><path d="M19 6l-1 14H6L5 6"></path><path d="M10 11v5"></path><path d="M14 11v5"></path></svg></button>
              <button class="move-up" type="button" title="위로 이동" aria-label="위로 이동"${index === 0 ? " disabled" : ""}>▲</button>
              <button class="move-down" type="button" title="아래로 이동" aria-label="아래로 이동"${index === slides.length - 1 ? " disabled" : ""}>▼</button>
            </div>`;
          item.querySelector(".page-title").textContent = slideTitle(slide);
          item.querySelector(".page-jump").addEventListener("click", () => {
            setActiveSlide(slide);
            slide.scrollIntoView({ behavior: "smooth", block: "center" });
          });
          item.querySelector(".delete-slide").addEventListener("click", () => deleteSlide(slide));
          item.querySelector(".move-up").addEventListener("click", () => moveSlide(slide, -1));
          item.querySelector(".move-down").addEventListener("click", () => moveSlide(slide, 1));
          list.appendChild(item);
        });
      };

      const renumberSlides = () => {
        orderedSlides().forEach((slide, index) => {
          const item = dataForSlide(slide);
          if (item?.fields?.page) slide.querySelector(".header .num").textContent = item.fields.page;
          else if (slide.querySelector(".header .num")) slide.querySelector(".header .num").textContent = String(index).padStart(2, "0");
        });
      };

      renderDeck();
      renderThemePicker();
      applyTheme(deckData.theme);
      writeDeckData();

      imageInput.addEventListener("change", () => {
        if (activeImageBox) readFile(activeImageBox, imageInput.files[0]);
        imageInput.value = "";
      });
      document.addEventListener("paste", (event) => {
        const box = document.activeElement.closest?.(".image-box") || activeImageBox;
        if (!box) return;
        const file = Array.from(event.clipboardData?.files || []).find((item) => item.type.startsWith("image/"));
        if (file) readFile(box, file);
      });
    })();
